[package]
name = "nymbazaar-server"
version = "0.1.0"
edition = "2021"

[dependencies]
nym-sdk = { git = "https://github.com/nymtech/nym", branch = "develop" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
